groups:
- name: scylla.rules
  rules:
  - alert: InstanceDown
    expr: up{job="scylla"} == 0
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} has been down for more than 30 seconds.'
      summary: Instance {{ $labels.instance }} down
  - alert: InstanceDown
    expr: absent(scylla_transport_requests_served{job="scylla", shard="0"})
    for: 1m
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} instance is shutting down.'
      summary: Instance {{ $labels.instance }} down
  - alert: InstanceDown
    expr: scylla_node_operation_mode > 3
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} instance is shutting down.'
      summary: Instance {{ $labels.instance }} down
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 25
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} has less than 25% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 10
    for: 30s
    labels:
      severity: "3"
    annotations:
      description: '{{ $labels.instance }} has less than 10% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 1
    for: 30s
    labels:
      severity: "4"
    annotations:
      description: '{{ $labels.instance }} has less than 1% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/"} / node_filesystem_size{mountpoint="/"}
      * 100 < 20
    for: 30s
    labels:
      severity: "3"
    annotations:
      description: '{{ $labels.instance }} has less than 20% free disk space on the root patition.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: NoCql
    expr: scylla_manager_healthcheck_cql_status == -1
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.host }} has denied cql connection for more than 30 seconds.'
      summary: Instance {{ $labels.host }} no cql connection
  - alert: HighLatencies
    expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket[300s])) by (instance, le)) > 100000
    for: 5m
    labels:
      severity: "1"
    annotations:
      description: '{{ $labels.instance }} has 95% high latency for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} Hight Write Latency
  - alert: HighLatencies
    expr: sum(rate(scylla_storage_proxy_coordinator_write_latency_sum[60s]))by (instance)/sum(rate(scylla_storage_proxy_coordinator_write_latency_count[60s]))by (instance) >10000
    for: 5m
    labels:
      severity: "1"
    annotations:
      description: '{{ $labels.instance }} has average high latency for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} Hight Write  Latency
  - alert: HighLatencies
    expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket[300s])) by (instance, le)) > 100000
    for: 5m
    labels:
      severity: "1"
    annotations:
      description: '{{ $labels.instance }} has 95% high latency for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} Hight Read Latency
  - alert: HighLatencies
    expr: sum(rate(scylla_storage_proxy_coordinator_read_latency_sum[60s]))by (instance)/sum(rate(scylla_storage_proxy_coordinator_read_latency_count[60s]))by (instance) >10000
    for: 5m
    labels:
      severity: "1"
    annotations:
      description: '{{ $labels.instance }} has average high latency for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} Hight Read  Latency
  - alert: BackupFailed
    expr: (sum(scylla_manager_task_run_total{type=~"backup", status="ERROR"}) or vector(0)) - (sum(scylla_manager_task_run_total{type=~"backup", status="ERROR"} offset 3m) or vector(0)) > 0
    for: 10s
    labels:
      severity: "1"
    annotations:
      description: 'Backup failed'
      summary: Backup task failed
  - alert: RepairFailed
    expr: (sum(scylla_manager_task_run_total{type=~"repair", status="ERROR"}) or vector(0)) - (sum(scylla_manager_task_run_total{type=~"repair", status="ERROR"} offset 3m) or vector(0)) > 0
    for: 10s
    labels:
      severity: "1"
    annotations:
      description: 'Repair failed'
      summary: Repair task failed
